# Generated by Django 4.0 on 2021-12-24 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('venue', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateTimeField()),
                ('lat_long', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='event.eventtype')),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
