# Generated by Django 4.0 on 2021-12-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_eventss'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Eventss',
        ),
    ]
