# Generated by Django 4.0 on 2022-01-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_favourite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='slug',
            field=models.CharField(max_length=255),
        ),
    ]
