# Generated by Django 4.0 on 2022-03-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favourite',
        ),
    ]
